[package]
name = "unknown91248/discordwebhook"
description = "Simple util to send discord webhooks"
authors = ["unknown91248"]
license = "MIT"
version = "0.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
promise = "evaera/promise@4.0.0"